version: "3.5"

services:
  files:
    image: marekful/webscp-files:rc-beta-3
    volumes:
      - ./database.db:/database.db
      - ./settings.json:/app/settings.json
      - /:/srv
    environment:
      - AGENT_ADDRESS=http://agent
      - INTERNAL_ADDRESS=http://files
      - UUID=1001
    ports:
      - "10.0.0.83:7080:80"

  agent:
    image: marekful/webscp-agent:rc-beta-3-alpine
    volumes:
      - /:/srv
      - data:/app/data
    environment:
      - FILES_ADDRESS=http://files
      - UUID=1001
    ports:
      - "8022:22"

volumes:
  data: