project_name: webscp

env:
  - GO111MODULE=on

build:
  env:
    - CGO_ENABLED=0
  ldflags:
    - -s -w -X github.com/marekful/webscp/version.Version={{ .Version }} -X github.com/marekful/webscp/version.CommitSHA={{ .ShortCommit }}
  main: main.go
  binary: webscp
  goos:
    - darwin
    - linux
    - windows
    - freebsd
  goarch:
    - amd64
    - 386
    - arm
    - arm64
  goarm:
    - 5
    - 6
    - 7
  ignore:
    - goos: darwin
      goarch: 386
    - goos: freebsd
      goarch: arm

archives:
  -
    name_template: "{{.Os}}-{{.Arch}}{{if .Arm}}v{{.Arm}}{{end}}-{{ .ProjectName }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

dockers:
  -
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64"
    goos: linux
    goarch: amd64
    image_templates:
      - "marekful/webscp:{{ .Tag }}-amd64"
      - "marekful/webscp:v{{ .Major }}-amd64"
    extra_files:
      - docker_config.json
  -
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/arm64"
    goos: linux
    goarch: arm64
    image_templates:
      - "marekful/webscp:{{ .Tag }}-arm64"
      - "marekful/webscp:v{{ .Major }}-arm64"
    extra_files:
      - docker_config.json
  -
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/arm/v6"
    goos: linux
    goarch: arm
    goarm: '6'
    image_templates:
      - "marekful/webscp:{{ .Tag }}-armv6"
      - "marekful/webscp:v{{ .Major }}-armv6"
    extra_files:
      - docker_config.json
  -
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/arm/v7"
    goos: linux
    goarch: arm
    goarm: '7'
    image_templates:
      - "marekful/webscp:{{ .Tag }}-armv7"
      - "marekful/webscp:v{{ .Major }}-armv7"
    extra_files:
      - docker_config.json
## s6 based docker images
  -
    dockerfile: Dockerfile.s6
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64"
    goos: linux
    goarch: amd64
    image_templates:
      - "marekful/webscp:{{ .Tag }}-amd64-s6"
      - "marekful/webscp:v{{ .Major }}-amd64-s6"
    extra_files:
      - docker/root
  -
    dockerfile: Dockerfile.s6.aarch64
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/arm64"
    goos: linux
    goarch: arm64
    image_templates:
      - "marekful/webscp:{{ .Tag }}-arm64-s6"
      - "marekful/webscp:v{{ .Major }}-arm64-s6"
    extra_files:
      - docker/root
  -
    dockerfile: Dockerfile.s6.armhf
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/arm/v6"
    goos: linux
    goarch: arm
    goarm: '6'
    image_templates:
      - "marekful/webscp:{{ .Tag }}-armv6-s6"
      - "marekful/webscp:v{{ .Major }}-armv6-s6"
    extra_files:
      - docker/root
  -
    dockerfile: Dockerfile.s6.armhf
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/arm/v7"
    goos: linux
    goarch: arm
    goarm: '7'
    image_templates:
      - "marekful/webscp:{{ .Tag }}-armv7-s6"
      - "marekful/webscp:v{{ .Major }}-armv7-s6"
    extra_files:
      - docker/root
docker_manifests:
  - name_template: "marekful/webscp:latest"
    image_templates:
      - "marekful/webscp:{{ .Tag }}-amd64"
      - "marekful/webscp:{{ .Tag }}-arm64"
      - "marekful/webscp:{{ .Tag }}-armv6"
      - "marekful/webscp:{{ .Tag }}-armv7"
  - name_template: "marekful/webscp:{{ .Tag }}"
    image_templates:
      - "marekful/webscp:{{ .Tag }}-amd64"
      - "marekful/webscp:{{ .Tag }}-arm64"
      - "marekful/webscp:{{ .Tag }}-armv6"
      - "marekful/webscp:{{ .Tag }}-armv7"
  - name_template: "marekful/webscp:v{{ .Major }}"
    image_templates:
      - "marekful/webscp:v{{ .Major }}-amd64"
      - "marekful/webscp:v{{ .Major }}-arm64"
      - "marekful/webscp:v{{ .Major }}-armv6"
      - "marekful/webscp:v{{ .Major }}-armv7"
## s6 image manifests
  - name_template: "marekful/webscp:s6"
    image_templates:
      - "marekful/webscp:{{ .Tag }}-amd64-s6"
      - "marekful/webscp:{{ .Tag }}-arm64-s6"
      - "marekful/webscp:{{ .Tag }}-armv6-s6"
      - "marekful/webscp:{{ .Tag }}-armv7-s6"
  - name_template: "marekful/webscp:{{ .Tag }}-s6"
    image_templates:
      - "marekful/webscp:{{ .Tag }}-amd64-s6"
      - "marekful/webscp:{{ .Tag }}-arm64-s6"
      - "marekful/webscp:{{ .Tag }}-armv6-s6"
      - "marekful/webscp:{{ .Tag }}-armv7-s6"
  - name_template: "marekful/webscp:v{{ .Major }}-s6"
    image_templates:
      - "marekful/webscp:v{{ .Major }}-amd64-s6"
      - "marekful/webscp:v{{ .Major }}-arm64-s6"
      - "marekful/webscp:v{{ .Major }}-armv6-s6"
      - "marekful/webscp:v{{ .Major }}-armv7-s6"
brews:
  - name: webscp
    tap:
      owner: marekful
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/marekful/webscp
    commit_author:
      name: WebSCP Robot
      email: robot@filebrowser.org
    description: WebSCP is a create-your-own-cloud-kind of software that you can install on a server, direct it to a path and then access your files through a nice web interface
    license: "MIT"